[project]
name = "project-sep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.1",
    "easyocr>=1.7.2",
    "jupyter>=1.1.1",
    "koreanize-matplotlib>=0.1.1",
    "matplotlib>=3.10.6",
    "numpy>=2.2.6",
    "opencv-python>=4.11.0.86",
    "openai>=1.107.3",
    "openpyxl>=3.1.5",
    "paddleocr>=3.2.0",
    "paddlepaddle>=3.2.0",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
    "rapidfuzz>=3.14.1",
    "roboflow>=1.2.9",
    "selenium>=4.35.0",
    "transformers>=4.56.1",
    "typing>=3.10.0.0",
    "seaborn>=0.13.2",
    "pydantic>=2.11.9",
    "ultralytics>=8.3.198",
    "undetected-chromedriver>=3.5.5",
    "uvicorn>=0.35.0",
    "pillow>=11.3.0",
    "tqdm>=4.67.1",
    "tensorboard>=2.20.0",
]
